export interface Release {
  version: string
  date: string
  type: 'major' | 'minor' | 'patch'
  title: string
  changes: string[]
}

export const releases: Release[] = [
  {
    version: '2.1.1',
    date: '2026-08-30',
    type: 'patch',
    title: '修复生产 SSR 启动报错',
    changes: [
      '修复生产部署 SSR 启动时 __exportAll$1 is not a function 报错',
    ],
  },
  {
    version: '2.1.0',
    date: '2026-08-30',
    type: 'minor',
    title: '依赖升级与 Better Auth / pnpm 集成修复',
    changes: [
      '包管理器从 Bun 迁移到 pnpm：删除 Bun runtime 依赖，测试改用 vitest，seed 脚本改走 tsx，README / scripts / .cta.json 同步',
      'framer-motion 替换为 motion（导入统一改为 motion/react 子路径）',
      '修复 Better Auth 1.7+ account.issuer 字段缺失导致的登录报 “User not found” 问题（迁移 0010）',
      'Better Auth drizzle adapter 切换到官方独立包 @better-auth/drizzle-adapter',
      'user 表 role / banned 字段加 NOT NULL + default，存量 NULL 行自动收敛为默认值（迁移 0011）',
      '修复 settings.linked-accounts 解绑 GitHub：unlinkAccount 调用改用 accountId 而非 providerId',
      '推送模板 vm 沙箱加固：sandbox 改 null-prototype，切断原型链逃逸',
      '删除无引用的 AnimatedOutlet 组件（dead code）'
    ],
  },
  {
    version: '2.0.0',
    date: '2026-07-24',
    type: 'major',
    title: '多渠道端点与推送架构升级',
    changes: [
      '端点由单渠道改为多渠道绑定，每个渠道独立校验、并行发送并分别记录执行日志',
      '重构推送请求协议：payload 承载消息数据，params 按渠道 ID 覆盖本次发送参数，渠道配置继续作为默认值',
      '渠道表单改为元数据驱动，端点关联渠道支持服务端搜索、分页多选与跨页选择保持',
      '日志增加原始请求记录、服务端分页和详情展示，并统一渠道、端点、日志与系统设置页面的视觉风格',
      '修复 Dashboard 图表统计字段类型错误，恢复推送趋势、渠道分布和端点排行展示',
      '移除未实际参与接口认证的系统级 API Key 功能及 api_keys 数据表',
      "移除 dayjs 依赖，消息模板改为直接使用 date-fns：${format(new Date(), 'yyyy-MM-dd HH:mm:ss')}",
      '新增 endpoint_channels 关联表迁移；升级前请备份数据库，旧端点 channel_id 与 api_keys 表将在迁移中调整或删除',
    ],
  },
  {
    version: '1.10.0',
    date: '2026-07-24',
    type: 'minor',
    title: '新增超级管理员与三级权限',
    changes: [
      '新增 super 超级管理员角色，形成普通用户、管理员、超级管理员三级权限体系',
      '管理员仅管理普通用户，邮件设置、对象存储和角色管理仅向超级管理员开放',
      '增加服务端越权拦截、角色变更会话失效以及最后一个可用超级管理员保护',
      '优化超级管理员初始化：已有 super 时跳过，否则优先提升现有 admin，无管理员时才创建新账号',
      '角色与种子策略测试统一迁移至独立 tests 目录',
    ],
  },
  {
    version: '1.9.0',
    date: '2026-07-20',
    type: 'minor',
    title: '新增主题配色预设',
    changes: [
      '新增颜色预设功能，内置默认、暖陶、地下森林、玫瑰花园等十套配色，可在页面顶部一键切换',
      '所选配色持久化保存，刷新后仍保持',
      '页面加载时提前写入主题与配色，避免刷新时出现配色闪烁',
    ],
  },
  {
    version: '1.8.3',
    date: '2026-07-20',
    type: 'patch',
    title: '修复主题切换动画与未登录跳转',
    changes: [
      '修复从深色切回浅色时主题切换动画会闪烁的问题',
      '未登录访问用户页面时改为先读会话再跳转登录页，避免错误登录状态被缓存',
    ],
  },
  {
    version: '1.8.2',
    date: '2026-07-11',
    type: 'patch',
    title: '修复 Dependabot 配置失效',
    changes: [
      '移除 Dependabot 中无对应工作流文件的 github-actions 生态块，避免其报 dependency_file_not_found 并导致整次更新运行失败',
    ],
  },
  {
    version: '1.8.1',
    date: '2026-07-04',
    type: 'patch',
    title: '头像加载提速',
    changes: ['资源中转地址增加浏览器缓存，刷新页面后头像更快显示'],
  },
  {
    version: '1.8.0',
    date: '2026-07-04',
    type: 'minor',
    title: '新增对象存储与文件上传能力',
    changes: [
      '新增「对象存储」管理页面，可在后台配置存储桶与访问域名',
      '提供通用上传接口，前端获取上传地址后直传，支持公开与私有桶',
      '个人设置页支持上传更换头像',
    ],
  },
  {
    version: '1.7.1',
    date: '2026-07-04',
    type: 'patch',
    title: '通知提示优化',
    changes: ['通知提示按类型显示不同颜色，并支持手动关闭'],
  },
  {
    version: '1.7.0',
    date: '2026-07-04',
    type: 'minor',
    title: '邮件服务支持页面配置',
    changes: [
      '邮件服务配置由环境变量迁移至管理后台「邮件设置」页面，支持 SMTP 与 Resend 两种传输方式',
      '新增 /email 管理页面，可在线配置并测试邮件发送',
    ],
  },
  {
    version: '1.6.4',
    date: '2026-07-04',
    type: 'patch',
    title: '修复 better-auth 会话类型推导',
    changes: [
      'Session 类型改用 authClient.getSession 的返回推导，替代 typeof auth.$Infer.Session，使 admin 插件注入的 role/banned 与 session.impersonatedBy 字段被正确推导',
      'trustedOrigins 对未定义的 BETTER_AUTH_URL 兜底空字符串，修复 TS 类型错误',
    ],
  },
  {
    version: '1.6.3',
    date: '2026-07-04',
    type: 'patch',
    title: 'shadcn 组件同步与新增聊天类组件',
    changes: [
      '新增 bubble、message、attachment、message-scroller、marker 五个聊天/AI 场景组件',
      'drawer 由 vaul 迁移至 @base-ui/react/drawer（Viewport+Popup 结构），新增 snapPoints/swipeDirection/showSwipeHandle 支持，移除已无引用的 vaul 依赖',
      '新增 @shadcn/react、date-fns 依赖（message-scroller 与 calendar 使用）',
      'sidebar 改为写 cookie 持久化展开状态，移除 ready 防闪烁逻辑',
      'calendar 补充 month_grid 样式，carousel 前后按钮改为 my-auto 垂直居中',
      'spinner 补充 data-slot，drawer description 增加 text-balance',
    ],
  },
  {
    version: '1.6.2',
    date: '2026-07-04',
    type: 'patch',
    title: '弹窗目录重组与冗余封装清理',
    changes: [
      'src/components/settings 目录更名为 users，与所属的用户管理页面对应',
      '弹窗组件去掉冗余的 User 维度命名（BanUserModal → BanModal 等），文件名同步简化',
      '新增 src/components/x/modal.tsx，基于 shadcn 封装通用弹窗组件',
      'use-theme 由 .tsx 拆为 .ts，移除未使用的 ThemeProvider/ThemeContext，根布局直接调用 useTheme',
      '移除未使用的 use-sidebar hook 与 mobileStore，改由 sidebarStore 统一管理',
      '移除 router 全局 MutationCache 的统一 toast 兜底，错误交由各 mutation 自行处理',
      '用户菜单「设置」项改用 render={<Link/>}，Avatar 合并 src 分支，确认邮件发送失败时抛出错误',
      'OpenAPI 文档标题从 package.json 的 name 改为 siteConfig.name，src/server/meta.ts 不再读取 name/description',
    ],
  },
  {
    version: '1.6.1',
    date: '2026-06-26',
    type: 'patch',
    title: '用户菜单可访问性与健壮性优化',
    changes: [
      '用户菜单触发按钮补充 aria-label，提升屏幕阅读器可访问性',
      '退出登录、退出模拟失败时新增 toast 错误提示，避免静默失败',
      '退出操作进行中禁用对应菜单项，防止重复触发',
      '用户菜单 user 属性改用 Session 类型推导，移除手写类型定义',
    ],
  },
  {
    version: '1.6.0',
    date: '2026-06-26',
    type: 'minor',
    title: 'Elysia 后端与文档系统重构',
    changes: [
      '后端接口统一迁移到 Elysia，拆分认证、更新日志、OpenAPI 等服务端模块',
      '认证接口改为 Better Auth 原生挂载，移除独立会话接口和多余兼容逻辑',
      'OpenAPI 页面改用 @elysia/openapi 官方 Scalar 渲染，并自动合并 Better Auth 文档',
      '接口文档补全中文标签、摘要和说明，版本信息从 package.json 自动读取',
      '移除配置页面，重新设计个人设置页面与用户菜单体验',
      '侧边栏折叠状态改为本地持久化，避免刷新时出现折叠再展开的闪烁',
      '修复 Calendar 组件在新版依赖下的显示与交互问题',
      '移除 GitHub Release 查询、user-context、query-keys 等不再需要的封装与接口',
      '首页调整为更克制的书信风格，减少大面积卡片背景',
    ],
  },
  {
    version: '1.5.1',
    date: '2026-06-17',
    type: 'patch',
    title: '统一常量管理',
    changes: [
      '统一常量目录（roles、routes、auth、cache、ui、i18n、animation、ban）',
      '消除全项目硬编码散落',
    ],
  },
  {
    version: '1.5.0',
    date: '2026-06-15',
    type: 'minor',
    title: '品牌系统重构与代码整理',
    changes: [
      '新增 siteConfig 集中管理站点名称与描述，消除多处硬编码',
      '重构 Logo 组件：variant 变体（full/icon）替代 collapsed 属性，移除 SiteIcon 独立组件',
      'Logo 组件迁移至 src/components/x/ 目录，统一业务组件归属',
      '移除 src/components/x/index.ts 桶文件，改为直接导入路径',
      '删除未使用的 SidebarNav 组件及 footerMenuItems 配置',
      '优化 seed 脚本：仅当数据库中不存在管理员时才创建，而非检查任意用户',
      '新增 Dependabot 自动依赖更新配置（bun + github-actions）',
    ],
  },
  {
    version: '1.4.0',
    date: '2026-06-13',
    type: 'minor',
    title: '数据库 Schema 与导航性能优化',
    changes: [
      '添加数据库 schema 和配置（account、session、user、verification 表）及 Drizzle 迁移文件',
      '修复退出登录和注册成功后用户路由上下文查询未清除的问题',
      '修复用户信息变更时的错误处理和回调 URL 更新',
      '优化导航性能：导航前调用 router.invalidate() 刷新路由',
      '优化导航性能：调整预加载过期时间，减少不必要的重新加载',
      '从 seed 脚本中移除默认站点配置',
      '.env.example 添加 VITE_SITE_NAME 变量',
      '升级 button、card、sidebar、toggle-group 等组件',
      '重构 use-mobile hook 实现',
    ],
  },
  {
    version: '1.3.1',
    date: '2026-05-10',
    type: 'patch',
    title: '用户头像与界面优化',
    changes: [
      '引入 boring-avatars 生成用户头像（beam 风格）',
      '新增自定义 Avatar 组件（src/components/x/avatar.tsx）',
      '用户菜单、个人资料页显示生成式头像',
      '用户管理页面添加头像列，响应式自适应布局',
      '表格支持 sm/md/lg 断点隐藏/显示列',
    ],
  },
  {
    version: '1.3.0',
    date: '2026-05-10',
    type: 'minor',
    title: '路由系统重构',
    changes: [
      '重构路由目录结构：从 _app/_auth 迁移到 _user/_public 双层架构',
      '新增公开路由：/login 登录页、/register 注册页、/ 公共首页',
      '用户路由优化：/dashboard、/profile、/users',
      '统一用户区域根路由 _user/route.tsx',
      '优化 Logo/SiteIcon 组件，移除不必要的依赖',
      '删除弃用的 API 路由 (favicon.ts)',
      '新增 vite-env.d.ts 类型定义',
    ],
  },
  {
    version: '1.2.3',
    date: '2026-05-06',
    type: 'patch',
    title: '性能优化',
    changes: [
      '启用 Better Auth Cookie 缓存，减少数据库查询',
      '优化 siteConfig 使用 TanStack Query 缓存',
    ],
  },
  {
    version: '1.2.2',
    date: '2026-05-06',
    type: 'patch',
    title: '优化 Logo 组件',
    changes: [
      'Logo 组件移除对 SidebarProvider 的依赖，可在任意上下文使用',
      '修复 _auth 布局使用 Logo 组件时的 context 错误',
    ],
  },
  {
    version: '1.2.1',
    date: '2026-05-06',
    type: 'patch',
    title: '统一文件命名风格',
    changes: [
      '简化 landing 目录组件命名（HeroSection → hero, FeaturesSection → features）',
      '简化 layout 目录组件命名（AppLogo → logo, ThemeToggle, UserMenu 等）',
      '简化 settings 目录组件命名（CreateUserModal → create-user-modal 等）',
      '统一 hooks 目录命名（useTheme → use-theme, useSidebar → use-sidebar）',
    ],
  },
  {
    version: '1.2.0',
    date: '2026-05-06',
    type: 'minor',
    title: '增强开发与服务端构建能力',
    changes: [
      '集成 TanStack Devtools Vite 插件，提升开发调试体验',
      '集成 Nitro Vite 插件，为服务端运行与构建提供支持',
    ],
  },
  {
    version: '1.1.2',
    date: '2026-05-05',
    type: 'patch',
    title: '修复侧边栏刷新闪烁',
    changes: ['侧边栏展开状态改为服务端读取 Cookie 初始化，避免刷新时先折叠后展开'],
  },
  {
    version: '1.1.1',
    date: '2026-05-02',
    type: 'patch',
    title: '优化侧边栏交互',
    changes: [
      '侧边栏默认折叠状态',
      '折叠时子菜单通过 Popover 弹出',
      '修复系统维护页面 Hydration 警告',
      '解决刷新页面时侧边栏闪烁问题',
    ],
  },
  {
    version: '1.1.0',
    date: '2026-05-01',
    type: 'minor',
    title: '主题重新设计',
    changes: ['新增暖色调主题（浅色/深色）', '优化边框与阴影样式', '增大圆角尺寸至 0.75rem'],
  },
  {
    version: '1.0.0',
    date: '2026-07-11',
    type: 'major',
    title: '迁移到 TanStack Start 模板',
    changes: [
      '以 tanstack-start-template 1.8.2 为基线重铺骨架：vite/tsconfig/drizzle 配置与 60+ shadcn/ui 组件逐字对齐，弃 React Compiler 与 vitest，接入 oxlint + oxfmt',
      '后端 8 个业务域（stats/channels/endpoints/logs/ai-presets/ai-providers/telegram/push）从 TanStack API Routes 迁到 Elysia 单体 + requireLogin macro，统一返回契约（成功裸对象、错误 status + {error}）',
      '渠道 schema 7 张业务表迁到模板路径 src/lib/db/schema/*，新增 relations.ts 与 auth userRelations 扩展；drizzle 0007 增量迁移（建 config 表、user/session ADD COLUMN），对生产数据安全',
      '前端 6 个业务路由归入侧边栏布局 _user/，URL 字面量不变；删旧顶部 AppHeader 与 relay auth 路由，复用模板的 _public 登录/注册与 GitHub OAuth',
      '渠道表单弃 react-hook-form，改为与模板 endpoint-form 一致的受控范式（channel-field + form-helpers 嵌套点路径读写）',
      '业务工具函数独立成 src/lib/crypto-tokens.ts（generateEndpointToken），不污染模板 utils.ts',
      '与 upstream 建立共同祖先（一次性 unrelated histories 合并），此后 git merge upstream 为标准三方合并，可持续享受模板更新',
    ],
  },
  {
    version: '0.9.1',
    date: '2026-07-05',
    type: 'patch',
    title: '端点表单 AI 插入与模板撤销重做',
    changes: [
      '修复端点表单点击「ai()」插入预设时报错 MenuGroupContext is missing：DropdownMenuLabel 未包裹在 DropdownMenuGroup 内，已用 DropdownMenuGroup 包裹预设列表项',
      'AI 预设项长名称改用 truncate 单行截断 + base-ui Tooltip，hover 300ms 显示完整名称，避免撑破菜单宽度',
      '消息模板支持 Ctrl+Z / Ctrl+Y 撤销重做：自管 undo/redo 历史栈，统一写入入口 commitTemplate，不再依赖 deprecated 的 document.execCommand',
    ],
  },
  {
    version: '0.9.0',
    date: '2025-06-13',
    type: 'minor',
    title: '渠道配置架构重构',
    changes: [
      '【Breaking】渠道配置从数据库 20 个扁平列迁移为单一 JSON config 字段，迁移前请备份数据库',
      '【Breaking】移除 @/lib/channels/senders/* 与 nodemailer，发送逻辑拆入 definitions/*.server.ts + senders.server.ts，邮件改用 @upyo/core + @upyo/smtp + @upyo/resend',
      '渠道配置统一为 JSON config 字段，支持任意渠道类型的灵活配置',
      '客户端/服务端代码隔离：含 Node.js 依赖的发送逻辑（飞书/钉钉 crypto、邮件 upyo）拆入 .server.ts，registry 仅导出客户端安全的元数据',
      '各渠道类型配置表单组件化，支持字段校验、密码输入、动态选项',
    ],
  },
]
