export interface Release {
  version: string
  date: string
  type: 'major' | 'minor' | 'patch'
  title: string
  changes: string[]
}

export const releases: Release[] = [
  {
    version: '1.6.0',
    date: '2026-06-26',
    type: 'minor',
    title: 'Elysia 后端与文档系统重构',
    changes: [
      '后端接口统一迁移到 Elysia，拆分认证、更新日志、OpenAPI 等服务端模块',
      '认证接口改为 Better Auth 原生挂载，移除独立会话接口和多余兼容逻辑',
      'OpenAPI 页面改用 @elysia/openapi 官方 Scalar 渲染，并自动合并 Better Auth 文档',
      '接口文档补全中文标签、摘要和说明，版本信息从 package.json 自动读取',
      '移除配置页面，重新设计个人设置页面与用户菜单体验',
      '侧边栏折叠状态改为本地持久化，避免刷新时出现折叠再展开的闪烁',
      '修复 Calendar 组件在新版依赖下的显示与交互问题',
      '移除 GitHub Release 查询、user-context、query-keys 等不再需要的封装与接口',
      '首页调整为更克制的书信风格，减少大面积卡片背景',
    ],
  },
  {
    version: '1.5.1',
    date: '2026-06-17',
    type: 'patch',
    title: '统一常量管理',
    changes: [
      '统一常量目录（roles、routes、auth、cache、ui、i18n、animation、ban）',
      '消除全项目硬编码散落',
    ],
  },
  {
    version: '1.5.0',
    date: '2026-06-15',
    type: 'minor',
    title: '品牌系统重构与代码整理',
    changes: [
      '新增 siteConfig 集中管理站点名称与描述，消除多处硬编码',
      '重构 Logo 组件：variant 变体（full/icon）替代 collapsed 属性，移除 SiteIcon 独立组件',
      'Logo 组件迁移至 src/components/x/ 目录，统一业务组件归属',
      '移除 src/components/x/index.ts 桶文件，改为直接导入路径',
      '删除未使用的 SidebarNav 组件及 footerMenuItems 配置',
      '优化 seed 脚本：仅当数据库中不存在管理员时才创建，而非检查任意用户',
      '新增 Dependabot 自动依赖更新配置（bun + github-actions）',
    ],
  },
  {
    version: '1.4.0',
    date: '2026-06-13',
    type: 'minor',
    title: '数据库 Schema 与导航性能优化',
    changes: [
      '添加数据库 schema 和配置（account、session、user、verification 表）及 Drizzle 迁移文件',
      '修复退出登录和注册成功后用户路由上下文查询未清除的问题',
      '修复用户信息变更时的错误处理和回调 URL 更新',
      '优化导航性能：导航前调用 router.invalidate() 刷新路由',
      '优化导航性能：调整预加载过期时间，减少不必要的重新加载',
      '从 seed 脚本中移除默认站点配置',
      '.env.example 添加 VITE_SITE_NAME 变量',
      '升级 button、card、sidebar、toggle-group 等组件',
      '重构 use-mobile hook 实现',
    ],
  },
  {
    version: '1.3.1',
    date: '2026-05-10',
    type: 'patch',
    title: '用户头像与界面优化',
    changes: [
      '引入 boring-avatars 生成用户头像（beam 风格）',
      '新增自定义 Avatar 组件（src/components/x/avatar.tsx）',
      '用户菜单、个人资料页显示生成式头像',
      '用户管理页面添加头像列，响应式自适应布局',
      '表格支持 sm/md/lg 断点隐藏/显示列',
    ],
  },
  {
    version: '1.3.0',
    date: '2026-05-10',
    type: 'minor',
    title: '路由系统重构',
    changes: [
      '重构路由目录结构：从 _app/_auth 迁移到 _user/_public 双层架构',
      '新增公开路由：/login 登录页、/register 注册页、/ 公共首页',
      '用户路由优化：/dashboard、/profile、/users',
      '统一用户区域根路由 _user/route.tsx',
      '优化 Logo/SiteIcon 组件，移除不必要的依赖',
      '删除弃用的 API 路由 (favicon.ts)',
      '新增 vite-env.d.ts 类型定义',
    ],
  },
  {
    version: '1.2.3',
    date: '2026-05-06',
    type: 'patch',
    title: '性能优化',
    changes: [
      '启用 Better Auth Cookie 缓存，减少数据库查询',
      '优化 siteConfig 使用 TanStack Query 缓存',
    ],
  },
  {
    version: '1.2.2',
    date: '2026-05-06',
    type: 'patch',
    title: '优化 Logo 组件',
    changes: [
      'Logo 组件移除对 SidebarProvider 的依赖，可在任意上下文使用',
      '修复 _auth 布局使用 Logo 组件时的 context 错误',
    ],
  },
  {
    version: '1.2.1',
    date: '2026-05-06',
    type: 'patch',
    title: '统一文件命名风格',
    changes: [
      '简化 landing 目录组件命名（HeroSection → hero, FeaturesSection → features）',
      '简化 layout 目录组件命名（AppLogo → logo, ThemeToggle, UserMenu 等）',
      '简化 settings 目录组件命名（CreateUserModal → create-user-modal 等）',
      '统一 hooks 目录命名（useTheme → use-theme, useSidebar → use-sidebar）',
    ],
  },
  {
    version: '1.2.0',
    date: '2026-05-06',
    type: 'minor',
    title: '增强开发与服务端构建能力',
    changes: [
      '集成 TanStack Devtools Vite 插件，提升开发调试体验',
      '集成 Nitro Vite 插件，为服务端运行与构建提供支持',
    ],
  },
  {
    version: '1.1.2',
    date: '2026-05-05',
    type: 'patch',
    title: '修复侧边栏刷新闪烁',
    changes: ['侧边栏展开状态改为服务端读取 Cookie 初始化，避免刷新时先折叠后展开'],
  },
  {
    version: '1.1.1',
    date: '2026-05-02',
    type: 'patch',
    title: '优化侧边栏交互',
    changes: [
      '侧边栏默认折叠状态',
      '折叠时子菜单通过 Popover 弹出',
      '修复系统维护页面 Hydration 警告',
      '解决刷新页面时侧边栏闪烁问题',
    ],
  },
  {
    version: '1.1.0',
    date: '2026-05-01',
    type: 'minor',
    title: '主题重新设计',
    changes: ['新增暖色调主题（浅色/深色）', '优化边框与阴影样式', '增大圆角尺寸至 0.75rem'],
  },
  {
    version: '1.0.0',
    date: '2026-05-01',
    type: 'major',
    title: '初始版本发布',
    changes: [
      '基于 TanStack Start 构建项目',
      '集成 Better-auth 认证系统',
      '配置 Drizzle ORM 数据库',
      '实现登录、注册页面',
      '完成侧边栏导航布局',
      '集成主题切换功能',
      '集成 sonner 消息通知',
      '集成 Motion 动画库',
      '集成 Recharts 图表库',
      '添加 shadcn/ui 组件库（60+ 组件）',
      '实现用户管理页面',
      '实现更新日志页面',
      '添加 Carousel 轮播组件',
      '添加 Field 输入域组件',
      '添加 Tooltip 提示组件',
      '配置 oxlint 代码检查工具',
      '配置 VSCode 格式化设置',
      '升级所有依赖到最新版本',
    ],
  },
]
