/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpenapiRouteImport } from './routes/openapi'
import { Route as UserRouteRouteImport } from './routes/_user/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as OpenapiSplatRouteImport } from './routes/openapi/$'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as UserProfileRouteImport } from './routes/_user/profile'
import { Route as PublicReleaseRouteImport } from './routes/_public/release'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as UserAdminRouteRouteImport } from './routes/_user/_admin/route'
import { Route as UserSettingsIndexRouteImport } from './routes/_user/settings/index'
import { Route as UserLogsIndexRouteImport } from './routes/_user/logs/index'
import { Route as UserEndpointsIndexRouteImport } from './routes/_user/endpoints/index'
import { Route as UserDashboardIndexRouteImport } from './routes/_user/dashboard/index'
import { Route as UserChannelsIndexRouteImport } from './routes/_user/channels/index'
import { Route as UserLogsIdRouteImport } from './routes/_user/logs/$id'
import { Route as UserEndpointsNewRouteImport } from './routes/_user/endpoints/new'
import { Route as UserChannelsNewRouteImport } from './routes/_user/channels/new'
import { Route as UserAdminUsersRouteImport } from './routes/_user/_admin/users'
import { Route as UserAdminStorageRouteImport } from './routes/_user/_admin/storage'
import { Route as UserAdminEmailRouteImport } from './routes/_user/_admin/email'
import { Route as UserEndpointsIdEditRouteImport } from './routes/_user/endpoints/$id/edit'
import { Route as UserChannelsIdEditRouteImport } from './routes/_user/channels/$id/edit'

const OpenapiRoute = OpenapiRouteImport.update({
  id: '/openapi',
  path: '/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const OpenapiSplatRoute = OpenapiSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => OpenapiRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRouteRoute,
} as any)
const PublicReleaseRoute = PublicReleaseRouteImport.update({
  id: '/release',
  path: '/release',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const UserAdminRouteRoute = UserAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserSettingsIndexRoute = UserSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserLogsIndexRoute = UserLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserEndpointsIndexRoute = UserEndpointsIndexRouteImport.update({
  id: '/endpoints/',
  path: '/endpoints/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserDashboardIndexRoute = UserDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserChannelsIndexRoute = UserChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserLogsIdRoute = UserLogsIdRouteImport.update({
  id: '/logs/$id',
  path: '/logs/$id',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserEndpointsNewRoute = UserEndpointsNewRouteImport.update({
  id: '/endpoints/new',
  path: '/endpoints/new',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserChannelsNewRoute = UserChannelsNewRouteImport.update({
  id: '/channels/new',
  path: '/channels/new',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserAdminUsersRoute = UserAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => UserAdminRouteRoute,
} as any)
const UserAdminStorageRoute = UserAdminStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => UserAdminRouteRoute,
} as any)
const UserAdminEmailRoute = UserAdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => UserAdminRouteRoute,
} as any)
const UserEndpointsIdEditRoute = UserEndpointsIdEditRouteImport.update({
  id: '/endpoints/$id/edit',
  path: '/endpoints/$id/edit',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserChannelsIdEditRoute = UserChannelsIdEditRouteImport.update({
  id: '/channels/$id/edit',
  path: '/channels/$id/edit',
  getParentRoute: () => UserRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/openapi': typeof OpenapiRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/release': typeof PublicReleaseRoute
  '/profile': typeof UserProfileRoute
  '/api/$': typeof ApiSplatRoute
  '/openapi/$': typeof OpenapiSplatRoute
  '/email': typeof UserAdminEmailRoute
  '/storage': typeof UserAdminStorageRoute
  '/users': typeof UserAdminUsersRoute
  '/channels/new': typeof UserChannelsNewRoute
  '/endpoints/new': typeof UserEndpointsNewRoute
  '/logs/$id': typeof UserLogsIdRoute
  '/channels/': typeof UserChannelsIndexRoute
  '/dashboard/': typeof UserDashboardIndexRoute
  '/endpoints/': typeof UserEndpointsIndexRoute
  '/logs/': typeof UserLogsIndexRoute
  '/settings/': typeof UserSettingsIndexRoute
  '/channels/$id/edit': typeof UserChannelsIdEditRoute
  '/endpoints/$id/edit': typeof UserEndpointsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/openapi': typeof OpenapiRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/release': typeof PublicReleaseRoute
  '/profile': typeof UserProfileRoute
  '/api/$': typeof ApiSplatRoute
  '/openapi/$': typeof OpenapiSplatRoute
  '/email': typeof UserAdminEmailRoute
  '/storage': typeof UserAdminStorageRoute
  '/users': typeof UserAdminUsersRoute
  '/channels/new': typeof UserChannelsNewRoute
  '/endpoints/new': typeof UserEndpointsNewRoute
  '/logs/$id': typeof UserLogsIdRoute
  '/channels': typeof UserChannelsIndexRoute
  '/dashboard': typeof UserDashboardIndexRoute
  '/endpoints': typeof UserEndpointsIndexRoute
  '/logs': typeof UserLogsIndexRoute
  '/settings': typeof UserSettingsIndexRoute
  '/channels/$id/edit': typeof UserChannelsIdEditRoute
  '/endpoints/$id/edit': typeof UserEndpointsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/_user': typeof UserRouteRouteWithChildren
  '/openapi': typeof OpenapiRouteWithChildren
  '/_user/_admin': typeof UserAdminRouteRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/release': typeof PublicReleaseRoute
  '/_user/profile': typeof UserProfileRoute
  '/api/$': typeof ApiSplatRoute
  '/openapi/$': typeof OpenapiSplatRoute
  '/_public/': typeof PublicIndexRoute
  '/_user/_admin/email': typeof UserAdminEmailRoute
  '/_user/_admin/storage': typeof UserAdminStorageRoute
  '/_user/_admin/users': typeof UserAdminUsersRoute
  '/_user/channels/new': typeof UserChannelsNewRoute
  '/_user/endpoints/new': typeof UserEndpointsNewRoute
  '/_user/logs/$id': typeof UserLogsIdRoute
  '/_user/channels/': typeof UserChannelsIndexRoute
  '/_user/dashboard/': typeof UserDashboardIndexRoute
  '/_user/endpoints/': typeof UserEndpointsIndexRoute
  '/_user/logs/': typeof UserLogsIndexRoute
  '/_user/settings/': typeof UserSettingsIndexRoute
  '/_user/channels/$id/edit': typeof UserChannelsIdEditRoute
  '/_user/endpoints/$id/edit': typeof UserEndpointsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/openapi'
    | '/login'
    | '/register'
    | '/release'
    | '/profile'
    | '/api/$'
    | '/openapi/$'
    | '/email'
    | '/storage'
    | '/users'
    | '/channels/new'
    | '/endpoints/new'
    | '/logs/$id'
    | '/channels/'
    | '/dashboard/'
    | '/endpoints/'
    | '/logs/'
    | '/settings/'
    | '/channels/$id/edit'
    | '/endpoints/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/openapi'
    | '/login'
    | '/register'
    | '/release'
    | '/profile'
    | '/api/$'
    | '/openapi/$'
    | '/email'
    | '/storage'
    | '/users'
    | '/channels/new'
    | '/endpoints/new'
    | '/logs/$id'
    | '/channels'
    | '/dashboard'
    | '/endpoints'
    | '/logs'
    | '/settings'
    | '/channels/$id/edit'
    | '/endpoints/$id/edit'
  id:
    | '__root__'
    | '/_public'
    | '/_user'
    | '/openapi'
    | '/_user/_admin'
    | '/_public/login'
    | '/_public/register'
    | '/_public/release'
    | '/_user/profile'
    | '/api/$'
    | '/openapi/$'
    | '/_public/'
    | '/_user/_admin/email'
    | '/_user/_admin/storage'
    | '/_user/_admin/users'
    | '/_user/channels/new'
    | '/_user/endpoints/new'
    | '/_user/logs/$id'
    | '/_user/channels/'
    | '/_user/dashboard/'
    | '/_user/endpoints/'
    | '/_user/logs/'
    | '/_user/settings/'
    | '/_user/channels/$id/edit'
    | '/_user/endpoints/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  OpenapiRoute: typeof OpenapiRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/openapi': {
      id: '/openapi'
      path: '/openapi'
      fullPath: '/openapi'
      preLoaderRoute: typeof OpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/openapi/$': {
      id: '/openapi/$'
      path: '/$'
      fullPath: '/openapi/$'
      preLoaderRoute: typeof OpenapiSplatRouteImport
      parentRoute: typeof OpenapiRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/profile': {
      id: '/_user/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_public/release': {
      id: '/_public/release'
      path: '/release'
      fullPath: '/release'
      preLoaderRoute: typeof PublicReleaseRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_user/_admin': {
      id: '/_user/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserAdminRouteRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/settings/': {
      id: '/_user/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof UserSettingsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/logs/': {
      id: '/_user/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof UserLogsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/endpoints/': {
      id: '/_user/endpoints/'
      path: '/endpoints'
      fullPath: '/endpoints/'
      preLoaderRoute: typeof UserEndpointsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/dashboard/': {
      id: '/_user/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof UserDashboardIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/channels/': {
      id: '/_user/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof UserChannelsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/logs/$id': {
      id: '/_user/logs/$id'
      path: '/logs/$id'
      fullPath: '/logs/$id'
      preLoaderRoute: typeof UserLogsIdRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/endpoints/new': {
      id: '/_user/endpoints/new'
      path: '/endpoints/new'
      fullPath: '/endpoints/new'
      preLoaderRoute: typeof UserEndpointsNewRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/channels/new': {
      id: '/_user/channels/new'
      path: '/channels/new'
      fullPath: '/channels/new'
      preLoaderRoute: typeof UserChannelsNewRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/_admin/users': {
      id: '/_user/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UserAdminUsersRouteImport
      parentRoute: typeof UserAdminRouteRoute
    }
    '/_user/_admin/storage': {
      id: '/_user/_admin/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof UserAdminStorageRouteImport
      parentRoute: typeof UserAdminRouteRoute
    }
    '/_user/_admin/email': {
      id: '/_user/_admin/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof UserAdminEmailRouteImport
      parentRoute: typeof UserAdminRouteRoute
    }
    '/_user/endpoints/$id/edit': {
      id: '/_user/endpoints/$id/edit'
      path: '/endpoints/$id/edit'
      fullPath: '/endpoints/$id/edit'
      preLoaderRoute: typeof UserEndpointsIdEditRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/channels/$id/edit': {
      id: '/_user/channels/$id/edit'
      path: '/channels/$id/edit'
      fullPath: '/channels/$id/edit'
      preLoaderRoute: typeof UserChannelsIdEditRouteImport
      parentRoute: typeof UserRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicReleaseRoute: typeof PublicReleaseRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicReleaseRoute: PublicReleaseRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface UserAdminRouteRouteChildren {
  UserAdminEmailRoute: typeof UserAdminEmailRoute
  UserAdminStorageRoute: typeof UserAdminStorageRoute
  UserAdminUsersRoute: typeof UserAdminUsersRoute
}

const UserAdminRouteRouteChildren: UserAdminRouteRouteChildren = {
  UserAdminEmailRoute: UserAdminEmailRoute,
  UserAdminStorageRoute: UserAdminStorageRoute,
  UserAdminUsersRoute: UserAdminUsersRoute,
}

const UserAdminRouteRouteWithChildren = UserAdminRouteRoute._addFileChildren(
  UserAdminRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserAdminRouteRoute: typeof UserAdminRouteRouteWithChildren
  UserProfileRoute: typeof UserProfileRoute
  UserChannelsNewRoute: typeof UserChannelsNewRoute
  UserEndpointsNewRoute: typeof UserEndpointsNewRoute
  UserLogsIdRoute: typeof UserLogsIdRoute
  UserChannelsIndexRoute: typeof UserChannelsIndexRoute
  UserDashboardIndexRoute: typeof UserDashboardIndexRoute
  UserEndpointsIndexRoute: typeof UserEndpointsIndexRoute
  UserLogsIndexRoute: typeof UserLogsIndexRoute
  UserSettingsIndexRoute: typeof UserSettingsIndexRoute
  UserChannelsIdEditRoute: typeof UserChannelsIdEditRoute
  UserEndpointsIdEditRoute: typeof UserEndpointsIdEditRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserAdminRouteRoute: UserAdminRouteRouteWithChildren,
  UserProfileRoute: UserProfileRoute,
  UserChannelsNewRoute: UserChannelsNewRoute,
  UserEndpointsNewRoute: UserEndpointsNewRoute,
  UserLogsIdRoute: UserLogsIdRoute,
  UserChannelsIndexRoute: UserChannelsIndexRoute,
  UserDashboardIndexRoute: UserDashboardIndexRoute,
  UserEndpointsIndexRoute: UserEndpointsIndexRoute,
  UserLogsIndexRoute: UserLogsIndexRoute,
  UserSettingsIndexRoute: UserSettingsIndexRoute,
  UserChannelsIdEditRoute: UserChannelsIdEditRoute,
  UserEndpointsIdEditRoute: UserEndpointsIdEditRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

interface OpenapiRouteChildren {
  OpenapiSplatRoute: typeof OpenapiSplatRoute
}

const OpenapiRouteChildren: OpenapiRouteChildren = {
  OpenapiSplatRoute: OpenapiSplatRoute,
}

const OpenapiRouteWithChildren =
  OpenapiRoute._addFileChildren(OpenapiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  OpenapiRoute: OpenapiRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
