/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ApiReleasesRouteImport } from './routes/api/releases'
import { Route as ApiFaviconRouteImport } from './routes/api/favicon'
import { Route as PublicReleaseRouteImport } from './routes/_public/release'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSystemRouteImport } from './routes/_app/system'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSystemIndexRouteImport } from './routes/_app/system/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppSystemMaintenanceRouteImport } from './routes/_app/system/maintenance'
import { Route as AppSystemInfoRouteImport } from './routes/_app/system/info'
import { Route as AppSettingsUsersRouteImport } from './routes/_app/settings/users'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ApiReleasesRoute = ApiReleasesRouteImport.update({
  id: '/api/releases',
  path: '/api/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFaviconRoute = ApiFaviconRouteImport.update({
  id: '/api/favicon',
  path: '/api/favicon',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicReleaseRoute = PublicReleaseRouteImport.update({
  id: '/release',
  path: '/release',
  getParentRoute: () => PublicRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemIndexRoute = AppSystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSystemRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSystemMaintenanceRoute = AppSystemMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppSystemRoute,
} as any)
const AppSystemInfoRoute = AppSystemInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => AppSystemRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/system': typeof AppSystemRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/release': typeof PublicReleaseRoute
  '/api/favicon': typeof ApiFaviconRoute
  '/api/releases': typeof ApiReleasesRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/system/info': typeof AppSystemInfoRoute
  '/system/maintenance': typeof AppSystemMaintenanceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/system/': typeof AppSystemIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/release': typeof PublicReleaseRoute
  '/api/favicon': typeof ApiFaviconRoute
  '/api/releases': typeof ApiReleasesRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/system/info': typeof AppSystemInfoRoute
  '/system/maintenance': typeof AppSystemMaintenanceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings': typeof AppSettingsIndexRoute
  '/system': typeof AppSystemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/system': typeof AppSystemRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_public/release': typeof PublicReleaseRoute
  '/api/favicon': typeof ApiFaviconRoute
  '/api/releases': typeof ApiReleasesRoute
  '/_public/': typeof PublicIndexRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/system/info': typeof AppSystemInfoRoute
  '/_app/system/maintenance': typeof AppSystemMaintenanceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/system/': typeof AppSystemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/dashboard'
    | '/settings'
    | '/system'
    | '/login'
    | '/register'
    | '/release'
    | '/api/favicon'
    | '/api/releases'
    | '/settings/users'
    | '/system/info'
    | '/system/maintenance'
    | '/api/auth/$'
    | '/settings/'
    | '/system/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/release'
    | '/api/favicon'
    | '/api/releases'
    | '/settings/users'
    | '/system/info'
    | '/system/maintenance'
    | '/api/auth/$'
    | '/settings'
    | '/system'
  id:
    | '__root__'
    | '/$'
    | '/_app'
    | '/_auth'
    | '/_public'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/system'
    | '/_auth/login'
    | '/_auth/register'
    | '/_public/release'
    | '/api/favicon'
    | '/api/releases'
    | '/_public/'
    | '/_app/settings/users'
    | '/_app/system/info'
    | '/_app/system/maintenance'
    | '/api/auth/$'
    | '/_app/settings/'
    | '/_app/system/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiFaviconRoute: typeof ApiFaviconRoute
  ApiReleasesRoute: typeof ApiReleasesRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/releases': {
      id: '/api/releases'
      path: '/api/releases'
      fullPath: '/api/releases'
      preLoaderRoute: typeof ApiReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/favicon': {
      id: '/api/favicon'
      path: '/api/favicon'
      fullPath: '/api/favicon'
      preLoaderRoute: typeof ApiFaviconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/release': {
      id: '/_public/release'
      path: '/release'
      fullPath: '/release'
      preLoaderRoute: typeof PublicReleaseRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/': {
      id: '/_app/system/'
      path: '/'
      fullPath: '/system/'
      preLoaderRoute: typeof AppSystemIndexRouteImport
      parentRoute: typeof AppSystemRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/system/maintenance': {
      id: '/_app/system/maintenance'
      path: '/maintenance'
      fullPath: '/system/maintenance'
      preLoaderRoute: typeof AppSystemMaintenanceRouteImport
      parentRoute: typeof AppSystemRoute
    }
    '/_app/system/info': {
      id: '/_app/system/info'
      path: '/info'
      fullPath: '/system/info'
      preLoaderRoute: typeof AppSystemInfoRouteImport
      parentRoute: typeof AppSystemRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppSystemRouteChildren {
  AppSystemInfoRoute: typeof AppSystemInfoRoute
  AppSystemMaintenanceRoute: typeof AppSystemMaintenanceRoute
  AppSystemIndexRoute: typeof AppSystemIndexRoute
}

const AppSystemRouteChildren: AppSystemRouteChildren = {
  AppSystemInfoRoute: AppSystemInfoRoute,
  AppSystemMaintenanceRoute: AppSystemMaintenanceRoute,
  AppSystemIndexRoute: AppSystemIndexRoute,
}

const AppSystemRouteWithChildren = AppSystemRoute._addFileChildren(
  AppSystemRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSystemRoute: typeof AppSystemRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSystemRoute: AppSystemRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicReleaseRoute: typeof PublicReleaseRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicReleaseRoute: PublicReleaseRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiFaviconRoute: ApiFaviconRoute,
  ApiReleasesRoute: ApiReleasesRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
